### ISSUE TITLE
error - ESXi 8.0 image not getting created

### ISSUE THREAD

**Issue by xiaocenter** [VFrontDe/ESXi-Customizer-PS#51] opened 2022-10-14 02:37 UTC
Connecting the VMware ESXi Software depot ... [OK]

Getting Imageprofiles, please wait ... [OK]

Using Imageprofile ESXi-8.0.0-20513097-standard ...
(Dated 09/23/2022 18:59:28, AcceptanceLevel: PartnerSupported,
The general availability release of VMware ESXi Server 8.0.0 brings whole new levels of virtualization performance to datacenters and enterprises.)

Exporting the Imageprofile to 'D:\\ESXi-8.0.0-20513097-standard.iso'. Please be patient ...

警告: The image profile fails validation.  The ISO / Offline Bundle will still be generated but may contain errors and
may not boot or be functional.  Errors:
警告:   File path of '/lib64/python3.8/xml/dom/minicompat.pyc' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.0-1.0.20513097', 'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
警告:   File path of '/lib64/python3.8/tkinter/font.pyc' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.0-1.0.20513097', 'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
警告:   File path of '/etc/vmware/default.map.d/intelnvdimm.map' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_native-misc-drivers_8.0.0-1.0.20513097',
'VMware_bootbank_native-misc-drivers-esxio_8.0.0-1.0.20513097'}
警告:   File path of '/usr/lib/vmware/vmkmod/vmkibft' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.0-1.0.20513097', 'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
警告:   File path of '/bin/esxcfg-volume' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.0-1.0.20513097', 'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
警告:   File path of '/etc/vmware/secpolicy/domains/ntpdDom' is claimed by multiple non-overlay VIBs:

**Comment by Turranius** [comment] 2022-10-14 12:41
Same here

PS C:\temp> .\ESXi-Customizer-PS-v2.9.0.ps1 -v80 -outDir "C:\Temp\Out" -NoSignatureCheck

This is ESXi-Customizer-PS Version 2.9.0 (visit https://ESXi-Customizer-PS.v-front.de for more information!)
(Call with -help for instructions)

Temporarily logging to C:\Users\mgr\AppData\Local\Temp\ESXi-Customizer-PS-9040.log ...

Running with PowerShell version 5.1 and VMware PowerCLI version 12.7.0 build 20091289

Connecting the VMware ESXi Software depot ... [OK]

Getting Imageprofiles, please wait ... [OK]

Using Imageprofile ESXi-8.0.0-20513097-standard ...
(Dated 09/23/2022 18:59:28, AcceptanceLevel: PartnerSupported,
The general availability release of VMware ESXi Server 8.0.0 brings whole new levels of virtualization performance to datacenters and enterprises.)

Exporting the Imageprofile to 'C:\Temp\Out\ESXi-8.0.0-20513097-standard.iso'. Please be patient ...

WARNING: The image profile fails validation.  The ISO / Offline Bundle will still be generated but may contain errors and may not boot or be functional.  Errors:
WARNING:   File path of '/lib64/python3.8/idlelib/idle_test/test_pathbrowser.pyc' is claimed by multiple non-overlay VIBs: {'VMware_bootbank_esx-base_8.0.0-1.0.20513097',
'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
WARNING:   File path of '/usr/lib/vmware/hostd/vimLocale/de/event.vmsg' is claimed by multiple non-overlay VIBs: {'VMware_bootbank_esx-base_8.0.0-1.0.20513097',
'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
WARNING:   File path of '/etc/rp.d/wsman.yml' is claimed by multiple non-overlay VIBs: {'VMware_bootbank_esx-base_8.0.0-1.0.20513097',
'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
WARNING:   File path of '/usr/libexec/jumpstart/plugins/libvmkapps.so' is claimed by multiple non-overlay VIBs: {'VMware_bootbank_esx-base_8.0.0-1.0.20513097',
'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
WARNING:   File path of '/usr/libexec/jumpstart/plugins/restore-system-swap.json' is claimed by multiple non-overlay VIBs: {'VMware_bootbank_esx-base_8.0.0-1.0.20513097',
'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
WARNING:   File path of '/lib64/python3.8/turtledemo/minimal_hanoi.pyc' is claimed by multiple non-overlay VIBs: {'VMware_bootbank_esx-base_8.0.0-1.0.20513097',
'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
WARNING:   File path of '/lib64/python3.8/gevent/resolver_thread.py' is claimed by multiple non-overlay VIBs: {'VMware_bootbank_esx-base_8.0.0-1.0.20513097',
'VMware_bootbank_esxio-base_8.0.0-1.0.20513097'}
[ESXi-8.0.0-20513097-standard.iso-202210141438.log](https://github.com/VFrontDe/ESXi-Customizer-PS/files/9786350/ESXi-8.0.0-20513097-standard.iso-202210141438.log)

**Comment by virtualex-itv** [comment] 2022-10-14 21:10
unfortunately - this is not an issue with the script.  I'm trying to research what could potentially be causing this to happen...

**Comment by VFrontDe** [comment] 2022-10-17 09:18
This error here is really a duplicate of the well known [WinError 10054] issue #15 .
At least with the latest PowerCLI versions the WARNING messages that appear with the ESXi 8.0 image profile are just warnings and do not prevent a successful export!

**Comment by xiaocenter** [comment] 2022-10-17 09:35
> This error here is really a duplicate of the well known [WinError 10054] issue #15 . At least with the latest PowerCLI versions the WARNING messages that appear with the ESXi 8.0 image profile are just warnings and do not prevent a successful export!

dont install

**Comment by Turranius** [comment] 2022-10-17 17:33
That is false. No image is created.

**Closed** 2022-10-18 15:37 UTC
Labels: bug, wontfix

**Comment by virtualex-itv** [comment] 2022-10-18 19:22
the current workaround is to export the image to an offline bundle (`.zip`) via `-oZip`, then re-running the script importing the offline bundle via `iZip` to convert it to an `.iso`

**Comment by fvlaicu** [comment] 2022-11-05 08:19
I think it is related to this: https://williamlam.com/2022/11/quick-tip-changes-to-building-custom-esxi-images-in-vsphere-8.html

**Comment by virtualex-itv** [comment] 2022-11-07 17:25
> I think it is related to this: [williamlam.com/2022/11/quick-tip-changes-to-building-custom-esxi-images-in-vsphere-8.html](https://williamlam.com/2022/11/quick-tip-changes-to-building-custom-esxi-images-in-vsphere-8.html)

it is... I am working on adding in some detections for this...

**Comment by virtualex-itv** [comment] 2022-11-09 14:52
made a few minor revisions for some "missing" things and added detections for PowerCLI version when trying to create an esxi 8.0 .iso.  please download and use the latest release found [here](https://github.com/VFrontDe-Org/ESXi-Customizer-PS/releases/tag/2.9.0)

**Comment by virtualex-itv** [comment] 2022-11-22 14:42
@xiaocenter @Turranius @fvlaicu @VFrontDe - this now works with the latest new release of `VMware.PowerCLI 13.0.0-20829139`.  

**Note:** To use the `VMware.ImageBuider` module, you must set the path to the Python 3.7 executable installed on your machine.

Please see [here](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/9619cb6d-3975-4bff-aa1f-0e785283a1a9/58d0925b-e15d-4803-bbd4-eb314dd165b0/GUID-EB16871E-D52B-4B46-9675-241AD42C1BE6.html) for more information.

![2022-11-22_09-35-45](https://user-images.githubusercontent.com/12056704/203342374-2d2e4d0b-be66-4533-9a16-45f8681b201f.png)
